# MySQL connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/logisticManagementSystemDb
spring.datasource.username=root
spring.datasource.password=hellowecp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update

server.port=5000



=======
spring.jpa.hibernate.ddl-auto=create

server.port=5000
>>>>>>> 1b4d1814d850f0219a666c7d9f66690b21047e46
